name: Add you configuration for new PGN connection 🚀 🖥️
description: Update configuration yaml file 
title: "Issue: Request PGN connection"
labels: ["demo"]

body:
  - type: input
    id: service_name
    attributes:
      label: Service Name
      description: Enter the name of the service (e.g., "artifactory-ehv").
    validations:
      required: true
  - type: textarea
    id: service_description
    attributes:
      label: Service Description
      description: Enter description of the service.
    validations:
      required: true
  - type: textarea
    id: owner_name
    attributes:
      label: Owner
      description: Enter the contact address of owner(s)
    validations:
      required: true
  - type: input
    id: bu_name
    attributes:
      label: Buissiness Unit Name
      description: Name of the owning business or `Global` if a global service
    validations:
      required: true
  - type: input
    id: dns_name
    attributes:
      label: DNS
      description: DNS 
  - type: textarea
    id: destination_cidrs
    attributes:
      label: Destination CIDRs
      description: Enter the destination CIDRs as a comma-separated list (e.g., "192.0.2.0, 198.51.100.0").
    validations:
      required: true
  - type: input
    id: destination_from_port
    attributes:
      label: Destination From Port
      description: Enter the destination from port (e.g., "443").
    validations:
      required: true
  - type: input
    id: destination_to_port
    attributes:
      label: Destination To Port
      description: Enter the destination to port (e.g., "443").
    validations:
      required: true
  - type: input
    id: protocols
    attributes:
      label: Protocols
      description: Enter the protocols as a comma-separated list (e.g., "6").
    validations:
      required: true
  - type: dropdown
    id: connection
    attributes:
      label: Connection
      description: Select the connection type.
      options:
        - direct
        - firewall
    validations:
      required: true
  - type: dropdown
    id: authentication
    attributes:
      label: Authentication
      description: Select the authentication type.
      options:
        - code1
        - other
    validations:
      required: true
- type: checkboxes
  id: use_ephimerals_ports
  attributes:
    label: Use Ephimerals Ports
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](link/to/coc)
        required: true
  - type: input
    id: landing_pages
    attributes:
      label: Landing Paghe(s)
      description: Enter the landing page(s) (e.g., "https://tools-server.htce.nl.philips.com/cicd_dashboard/").
    validations:
      required: true
