name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Changelog
        id: changelog
        uses: srepollock/changelog-generator-action@master
        with:
          REPO_NAME: 'Prateek-Wayne/MyGIthubAction'
          ACCESS_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          PATH: '/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "${{ steps.changelog.outputs.commit_message }}"
          git push
