name: "New Issue"

on:
  issues:
    types: [opened, reopened]
   
jobs:
  newIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
